### PR TITLE
Moved to l4re-snapshot 21.7

### PR DESCRIPTION
**Pull request by sevenautumns**
I tried bringing the master branch to snapshot version 21.7.  
In the process I somewhat disconnected the master branch.

What I did:
- Change to the upstream branch
- Copy the new snapshot 21.7 to the directory
- Rebase master onto upstream
   - Skip 4349879 and 82a4c73 (Where 18.7 was committed) 
- Change files expecting the location of fiasco to be in `src/kernel/fiasco` instead of the new `src/fiasco` with 875e688
- Made some minor adjustments to some of the Rust code with f723d09 so that `make` completes `make` successful.

I only tested the result for amd64 with `make qemu`.
Both the `hello-shared` and Rust based `two_task_ipc` seem to work perfectly.

### CODE REVIEW

**Comment by humenda** [comment]
Wow, this is pretty awesome! I have been wanting this for a long time and
didn't make any progress due to lack of time. Please give me a few days to
review.

**Comment by sevenautumns** [comment]
> Wow, this is pretty awesome! I have been wanting this for a long time and didn't make any progress due to lack of time. Please give me a few days to review.

Glad to hear that.
Ill take from the files in this folder:  
https://github.com/humenda/rustl4re/tree/master/src/l4/mk/arch  
that this project is not expected to succeed for other architectures than `amd64`, am I correct with that assumption?
Would further contributions regarding support for `arm` be welcome?

**Comment by humenda** [comment]
Is there a chance you could rebase your work such that upstream contains the
current snapshot, i.e. a second commit to the first snapshot and rebase master
onto it?
Ideally, I'd like to have a workflow similar to the one of git-buildpackage,
but I'm not sure how to do a merge from upstream to master that doesn't delete
the files added on master.

**Comment by sevenautumns** [comment]
I dont quite understand.  
How should the commit history of `master` be structured afterwards

Right now your `master` branch is structured like this:  
*Initial commit of l4re-snapshot 18.7* -- *strip l4linux* -- implementation of l4rust  
The first two commits are taken from `upstream`

My `master` branch is structured like this:
*Initial commit of l4re-snapshot 18.7* -- *strip l4linux* -- *Update to l4re-snapshot 21.7*` -- **rebased** implementation of l4rust -- fixes for 21.7

I understand that `upstream` should either look like this:
*Initial commit of l4re-snapshot 18.7* -- *strip l4linux* -- *Update to l4re-snapshot 21.7*
or:
*Initial commit of l4re-snapshot 18.7* -- *Update to l4re-snapshot 21.7* -- *strip l4linux*

But what should my pull request `master` look like to be compliant ?

**Comment by humenda** [comment]
It looks strange with the 0 commits merged, but it got merged :).

**Pull request merged**
